apiVersion: 2019-12-01
location: westus
name: <ACI_NAME>
properties:
  imageRegistryCredentials: # Credentials to pull a private image
  - server: <DOCKER_REGISTRY_URL>
    username: <DOCKER_REGISTRY_USERNAME>
    password: <DOCKER_REGISTRY_PASSWORD>
  networkProfile:
    id: <NETWORK_PROFILE_ID>
  containers:
  - name: sqlapi
    properties:
      image: <DOCKER_REGISTRY_URL>/azurefriday/api:<GIT_SHA>
      environmentVariables:
      - name: SQL_SERVER_FQDN
        value: <SQL_SERVER_FQDN>
      - name: SQL_SERVER_USERNAME
        value: <SQL_SERVER_USERNAME>
      - name: SQL_SERVER_DB
        value: <SQL_SERVER_DB>
      - name: SQL_SERVER_PASSWORD
        secureValue: <SQL_SERVER_PASSWORD>
      ports:
      - port: 8080
        protocol: TCP
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1
      volumeMounts:
  volumes:
  ipAddress:
    ports:
    - port: 80
      protocol: TCP
    type: Private
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups