name: Pull Request Closed

on:
  pull_request:
    types: [closed]
    
env:
  # basic  
  resourceGroup: azurefriday
  location: eastus
  subName: "ca-jessde-demo-test"

  # app specific
  prAcrName: azurefridaypr21
  keyvault_name: azurefriday21

  # storage
  storage_account_name: acijdimgresfq3snhzfq

  # aci
  pr_image_name: jd-image-pr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR Azure Container Instance
        run: |
          az container delete \
            -g $resourceGroup \
            -n $pr_image_name -y